---
- name: Check already installed
  command: lxc-config -l
  register: already_installed
  ignore_errors: True

- name: Create source directory
  file: path={{ lxc_dev_src_path }}
        state=directory
        mode=0755
        owner={{ lxc_dev_user }}
  when: already_installed|failed

- name: Clone lxc sources
  git: repo={{ lxc_dev_git_repository }}
       dest={{ lxc_dev_src_path }}/lxc
       accept_hostkey=yes
  remote_user: "{{ lxc_dev_user }}"
  when: already_installed|failed

- name: Make lxc
  command: "{{ item }}"
  args:
    chdir: "{{ lxc_dev_src_path }}/lxc"
  remote_user: "{{ lxc_dev_user }}"
  with_items:
    - ./autogen.sh
    - ./configure
    - make
  when: already_installed|failed

- name: Install lxc
  command: "{{ item }}"
  args:
    chdir: "{{ lxc_dev_src_path }}/lxc"
  with_items:
    - make install
    - ldconfig
  when: already_installed|failed

- name: Check lxc install
  command: lxc-config -l

- name: Enable bridge for lxc-net service
  lineinfile: dest=/etc/default/lxc
              regexp='^USE_LXC_BRIDGE=.*$'
              line='USE_LXC_BRIDGE="true"'
  when: lxc_dev_enable_bridge

- name: Ensure bridge for lxc-net service
  replace: dest=/etc/default/lxc
           regexp='^USE_LXC_BRIDGE=.*$'
           replace='USE_LXC_BRIDGE="true"'
  when: lxc_dev_enable_bridge

- name: Ensure dnsmasq for lxc-net service
  lineinfile: dest=/etc/network/interfaces
              regexp='^LXC_DHCP_CONFILE=.*$'
              line='LXC_DHCP_CONFILE="/etc/lxc/dnsmasq.conf"'

- name: Restart lxc-net service
  command: /usr/local/libexec/lxc/lxc-net restart

- name: Restart lxcbr0 interface
  command: ifconfig lxcbr0 up
  when: lxc_dev_enable_bridge

- name: Write lxc config for dnsmasq
  template: src=templates/etc/dnsmasq.d/50-lxc.tmpl
            dest=/etc/dnsmasq.d/50-lxc
            mode=0655
            owner=root
            group=root
  when: lxc_dev_enable_dnsmasq

- name: Restart dnsmasq
  service: name=dnsmasq state=restarted
  when: lxc_dev_enable_dnsmasq

- name: Install ansible lxc-python2 requirement
  pip: name=lxc-python2
