---
- name: Check already installed
  command: lxc-config -l
  register: already_installed
  ignore_errors: True

- name: Create source directory
  file:
    mode: 0755
    owner: '{{ lxc_dev_user }}'
    path: '{{ lxc_dev_src_path }}'
    state: directory
  when: already_installed|failed

- name: Clone lxc sources
  git:
    accept_hostkey: yes
    dest: '{{ lxc_dev_src_path }}/lxc'
    repo: '{{ lxc_dev_git_repository }}'
  remote_user: '{{ lxc_dev_user }}'
  when: already_installed|failed

- name: Make lxc
  command: '{{ item }}'
  args:
    chdir: '{{ lxc_dev_src_path }}/lxc'
  remote_user: '{{ lxc_dev_user }}'
  with_items:
    - ./autogen.sh
    - ./configure --libdir=/lib --localstatedir=/var --sysconfdir=/etc
    - make
  when: already_installed|failed

- name: Install lxc
  command: '{{ item }}'
  args:
    chdir: '{{ lxc_dev_src_path }}/lxc'
  with_items:
    - make install
    - ldconfig
  when: already_installed|failed

- name: Check lxc install
  command: lxc-config -l

- name: Install ansible lxc-python2 requirement
  pip:
    name: lxc-python2
    executable: '{{ lxc_dev_pip_executable }}'

- name: Write lxc config files
  template:
    dest: '/etc/lxc/{{ item }}.conf'
    src: '{{ templates_root }}/etc/lxc/{{ item }}.conf.j2'
  with_items:
    - default
    - dnsmasq

- name: Ensure dnsmasq bind-interfaces
  lineinfile:
    dest: /etc/dnsmasq.conf
    line: 'bind-interfaces'
    regexp: '^#bind-interfaces'
  when: lxc_dev_enable_dnsmasq

- name: Write lxc config for dnsmasq
  template:
    dest: /etc/dnsmasq.d/50-lxc
    src: '{{ templates_root }}/etc/dnsmasq.d/50-lxc.j2'
  when: lxc_dev_enable_dnsmasq

- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  when: lxc_dev_enable_dnsmasq

- name: Enable bridge for lxc-net service
  lineinfile:
    dest: /etc/default/lxc
    line: 'USE_LXC_BRIDGE="true"'
    regexp: '^USE_LXC_BRIDGE=.*$'
  when: lxc_dev_enable_bridge

- name: Ensure dnsmasq for lxc-net service
  lineinfile:
    dest: /etc/default/lxc
    line: 'LXC_DHCP_CONFILE="/etc/lxc/dnsmasq.conf"'
    regexp: '^LXC_DHCP_CONFILE=.*$'
  when: lxc_dev_enable_bridge

- name: Write lxc config for dnsmasq
  template:
    dest: /etc/default/lxc-net
    src: '{{ templates_root }}/etc/default/lxc-net.j2'
  when: lxc_dev_enable_bridge

- name: Ensure lxc domain for lxc-net service
  lineinfile:
    create: yes
    dest: /etc/default/lxc-net
    line: 'LXC_DOMAIN=lxc'
    state: present
  when: lxc_dev_enable_bridge

- name: Restart lxc-net service
  command: systemctl restart lxc-net
  when: lxc_dev_enable_bridge

- name: Enable lxc-net service at start
  command: systemctl enable lxc-net
  when: lxc_dev_enable_bridge

- name: Restart lxcbr0 interface
  command: ifconfig lxcbr0 up
  when: lxc_dev_enable_bridge

- name: Update resolvconf
  command: resolvconf -u
  when: lxc_dev_enable_dnsmasq or lxc_dev_enable_bridge
